app/src/Entity/SettingBrand.php
<?php

namespace App\Entity;

use App\Repository\SettingBrandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SettingBrandRepository::class)]
#[ORM\Table(name: 'setting_brand')]
#[ORM\Index(name: 'setting_brand_idx', columns: ['slug'])]
#[ORM\HasLifecycleCallbacks]
#[Gedmo\Loggable]
#[Gedmo\SoftDeleteable(fieldName: 'deletedAt', timeAware: false, hardDelete: true)]
#[UniqueEntity(fields: ['name'])]
class SettingBrand
{
    /**
     * Hook timestamp behavior
     * updates createdAt, updatedAt fields
     * Hook SoftDeleteable behavior
     * updates deletedAt field.
     */
    use TimestampableEntity;
    use SoftDeleteableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 64, unique:true, nullable:false)]
    #[Assert\Length(min: 1, max: 64)]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    #[Groups(['index'])]
    #[Gedmo\Versioned]
    private string $name;

    #[ORM\Column(type: Types::SMALLINT, nullable: false, options: ['default' => 0, 'unsigned' => true])]
    #[Assert\PositiveOrZero]
    #[Groups(['index'])]
    #[Gedmo\Versioned]
    private int $cars_number = 0;

    #[ORM\Column(type: Types::STRING, length: 64, unique: true, nullable: false)]
    #[Gedmo\Slug(fields: ['name'], separator: '-')]
    #[Gedmo\Versioned]
    private string $slug;

    #[ORM\OneToMany(targetEntity: GarageApp::class, mappedBy: 'settingBrand')]
    protected Collection $garage;

    public function __construct()
    {
        $this->garage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCarsNumber(): ?int
    {
        return $this->cars_number;
    }

    public function setCarsNumber(int $cars_number): static
    {
        $this->cars_number = $cars_number;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, GarageApp>
     */
    public function getGarage(): Collection
    {
        return $this->garage;
    }

    public function addGarage(GarageApp $garage): static
    {
        if (!$this->garage->contains($garage)) {
            $this->garage->add($garage);
            $garage->setSettingBrand($this);
        }

        return $this;
    }

    public function removeGarage(GarageApp $garage): static
    {
        if ($this->garage->removeElement($garage)) {
            // set the owning side to null (unless already changed)
            if ($garage->getSettingBrand() === $this) {
                $garage->setSettingBrand(null);
            }
        }

        return $this;
    }
}

app/src/Controller/Front/Garage/CreateController.php
<?php

namespace App\Controller\Front\Garage;

use App\Entity\GarageApp;
use App\Event\Garage\CreateEvent;
use App\Event\Setting\BrandEvent;
use App\Event\Setting\ClassEvent;
use App\Form\Front\GarageAppCreateType;
use App\Service\Cache\GarageAppService;
use App\Trait\Controller\WebTrait;
use Doctrine\ORM\EntityManagerInterface;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/{_locale<%app.supported_locales%>}/garage', name: 'app.garage.', options: ['expose' => false], schemes: ['http', 'https'], format: 'html', utf8: true)]
final class CreateController extends AbstractController
{
    use WebTrait;

    /** @description link to the index page */
    private static string $index = 'app.garage.index';

    /** @description link to the create page */
    private static string $create = 'app.garage.create';

    /** @description link to the delete page */
    private static string $delete = 'app.garage.delete';

    /**
     * @param GarageAppService $service
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param EventDispatcherInterface $dispatcher
     * @param TranslatorInterface $translator
     * @return Response
     */
    #[Route('/create.php', name: 'create', methods: ['GET', 'POST'])]
    public function create(
        GarageAppService $service,
        Request $request,
        EntityManagerInterface $manager,
        EventDispatcherInterface $dispatcher,
        TranslatorInterface $translator,
    ): Response
    {
        // Variables
        $title = $translator->trans('text.create.car');

        // Création du formulaire
        $garage = new GarageApp();
        $form = $this->createForm(GarageAppCreateType::class, $garage)->handleRequest($request);

        // Vérification des données du formulaire
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                // Event
                $dispatcher->dispatch(new BrandEvent($garage));
                $dispatcher->dispatch(new ClassEvent($garage));
                $dispatcher->dispatch(new CreateEvent($garage));

                // Doctrine
                $manager->persist($garage);
                $manager->flush();

                // Cache
                $service->cacheDelete();

                // Flash Message
                $this->addFlash('success', [
                    'title' => $translator->trans('text.garage'),
                    'message' => sprintf(
                        $translator->trans('notification.created'),
                        $garage->getSettingBrand()->getName() . ' ' . $garage->getModel()
                    )
                ]);

            } catch (RuntimeException $e) {
                // Flash Message
                $this->addFlash('danger', [
                    'title' => $translator->trans('text.garage'),
                    'message' => $translator->trans('notification.error'),
                ]);
                throw new RuntimeException($e->getMessage(), $e->getCode(), $e);
            }

            // Redirection
            return $this->redirectToIndex();
        }

        return $this->render('@App/front/contents/garage/create.html.twig', [
            'controller_name'  => $title,
            'current_page'     => $request->attributes->get('_route'),
            'container'        => 'container',
            'breadcrumb'       => ['level1' => $translator->trans('text.garage'), 'level2' => $title],
            'links'            => self::getLinksPage(),
            'garage'           => $garage,
            'game_update_last' => $manager->getRepository(GarageApp::class)->getLastUpdate(),
            'form'             => $form,
        ]);
    }
}

app/src/Controller/Front/Garage/ReadController.php
<?php

namespace App\Controller\Front\Garage;

use App\Entity\GarageApp;
use App\Trait\Controller\WebTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/{_locale<%app.supported_locales%>}/garage', name: 'app.garage.', options: ['expose' => false], schemes: ['http', 'https'], format: 'html', utf8: true)]
final class ReadController extends AbstractController
{
    use WebTrait;

    /** @description link to the index page */
    private static string $index = 'app.garage.index';

    /** @description link to the create page */
    private static string $create = 'app.garage.create';

    /** @description link to the delete page */
    private static string $delete = 'app.garage.delete';

    /**
     * @param Request $request
     * @param GarageApp $garage
     * @param EntityManagerInterface $manager
     * @param TranslatorInterface $translator
     * @return Response
     */
    #[Route('/read/{slug}-{id}.php', name: 'read', requirements: ['id' => Requirement::DIGITS, 'slug' => Requirement::ASCII_SLUG], methods: ['GET'])]
    public function read(
        Request $request,
        GarageApp $garage,
        EntityManagerInterface $manager,
        TranslatorInterface $translator,
    ): Response
    {
        // Entity
        $entity = $manager->getRepository(GarageApp::class)->getGarageOne($garage->getId(), $garage->getSlug());

        // Variables
        $title = $entity['brand'] . ' ' . $entity['model'];

        return $this->render('@App/front/contents/garage/read.html.twig', [
            'controller_name' => $title,
            'current_page'    => $request->attributes->get('_route'),
            'container'       => 'container',
            'breadcrumb'      => ['level1' => $translator->trans('text.garage'), 'level2' => $translator->trans('text.read')],
            'links'           => self::getLinksPage(),
            'entity'          => $entity,
            'car'             => $title,
        ]);
    }
}

app/src/Controller/Front/Garage/UpdateController.php
<?php

namespace App\Controller\Front\Garage;

use App\Entity\GarageApp;
use App\Event\Garage\UpdateEvent;
use App\Form\Front\GarageAppUpdateType;
use App\Service\Cache\GarageAppService;
use App\Trait\Controller\WebTrait;
use Doctrine\ORM\EntityManagerInterface;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/{_locale<%app.supported_locales%>}/garage', name: 'app.garage.', options: ['expose' => false], schemes: ['http', 'https'], format: 'html', utf8: true)]
final class UpdateController extends AbstractController
{
    use WebTrait;

    /** @description link to the index page */
    private static string $index = 'app.garage.index';

    /** @description link to the create page */
    private static string $create = 'app.garage.create';

    /** @description link to the delete page */
    private static string $delete = 'app.garage.delete';

    /**
     * @param Request $request
     * @param GarageApp $entity
     * @param GarageAppService $cache
     * @param EntityManagerInterface $manager
     * @param EventDispatcherInterface $dispatcher
     * @param TranslatorInterface $translator
     * @return Response
     */
    #[Route('/update/{slug}-{id}.php', name: 'update', requirements: ['id' => Requirement::DIGITS, 'slug' => Requirement::ASCII_SLUG], methods: ['GET', 'POST'])]
    public function update(
        Request $request,
        GarageApp $entity,
        GarageAppService $cache,
        EntityManagerInterface $manager,
        EventDispatcherInterface $dispatcher,
        TranslatorInterface $translator,
    ): Response
    {
        // Variables
        $car   = $entity->getSettingBrand()->getName() . ' ' . $entity->getModel();

        // Création du Formulaire
        $form = $this->createForm(GarageAppUpdateType::class, $entity)->handleRequest($request);

        // Vérification des données du formulaire
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                // Event
                $dispatcher->dispatch(new UpdateEvent($entity));

                // Doctrine
                $manager->flush();

                // Cache
                $cache->cacheDelete();

                // Flash Message
                $this->addFlash('info', [
                    'title' => $translator->trans('text.garage'),
                    'message' => sprintf($translator->trans('notification.updated'), $car)
                ]);

            } catch (RuntimeException $e) {
                // Flash Message
                $this->addFlash('danger', [
                    'title' => $translator->trans('text.garage'),
                    'message' => $translator->trans('notification.error'),
                ]);
                throw new RuntimeException($e->getMessage(), $e->getCode(), $e);
            }

            // Redirection
             return $this->redirectToRoute('app.garage.update', ['slug' => $entity->getSlug(), 'id' => $entity->getId()]);
        }

        // Logs
//        $logApp         = $manager->getRepository(LogEntry::class)->getLogEntries($entity);
//        $logBlue        = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getBlueprint()->getValues()[0]);
//        $logGauntlet    = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getGauntlet()->getValues()[0]);
//        $logRank        = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getRank()->getValues()[0]);
//        $logStatus      = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getStatus()->getValues()[0]);
//        $logActual      = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getStatActual()->getValues()[0]);
//        $logMax         = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getStatMax()->getValues()[0]);
//        $logMin         = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getStatMin()->getValues()[0]);
//        $logUpgrades    = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getUpgrade()->getValues()[0]);
//        $logBlueprint   = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getSettingBlueprint());
//        $logBrand       = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getSettingBrand());
//        $logClass       = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getSettingClass());
//        $logLevel       = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getSettingLevel());
//        $logPrice       = $manager->getRepository(LogEntry::class)->getLogEntries($entity->getSettingUnitPrice());
//        $logs           = array_merge($logApp,
//            $logBlue, $logGauntlet, $logRank, $logStatus, $logActual, $logMax, $logMin, $logUpgrades,
//            $logBlueprint, $logBrand, $logClass, $logLevel, $logPrice
//        );
//        /** @var LogEntry $logs */
//        dd($logs[0]->getLoggedAt()->format('Y-m-d H:i'));

        return $this->render('@App/front/contents/garage/update.html.twig', [
            'controller_name' => $car,
            'current_page'    => $request->attributes->get('_route'),
            'container'       => 'container-fluid', // container-fluid
            'breadcrumb'      => ['level1' => $translator->trans('text.garage'), 'level2' => $translator->trans('text.update')],
            'links'           => self::getLinksPage(),
            'entity'          => $entity,
            'form'            => $form,
            'car'             => $car,
        ]);
    }

    /**
     * @param Request $request
     * @param GarageApp $garage
     * @param EntityManagerInterface $manager
     * @param TranslatorInterface $translator
     * @return Response
     */
    #[Route('/delete/{id}', name: 'delete', requirements: ['id' => Requirement::DIGITS], methods: ['POST'])]
    public function delete(Request $request, GarageApp $garage, EntityManagerInterface $manager, TranslatorInterface $translator): Response
    {
        if ($this->isCsrfTokenValid('delete'.$garage->getId(), $request->getPayload()->getString('_token'))) {
            $manager->remove($garage);
            $manager->flush();

            // Flash Message
            $this->addFlash('error', [
                'title' => $translator->trans('text.garage'),
                'message' => sprintf($translator->trans('notification.deleted'),
                    $garage->getSettingBrand()->getName() . " " . $garage->getModel()
                )
            ]);
        }

        return $this->redirectToIndex();
    }
}

app/templates/front/contents/garage/update/_blueprint.html.twig
{#<section class="{{ container|default('container') }} mb-2 px-0">#}
<div class="col-9">
    <h2 class="text-center">{{ 'text.blueprint'|trans|plural }}</h2>
    <table class="table table-striped table-bordered mb-0">
        <thead>
            <tr>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star1) }}</th>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star2) }}</th>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star3) }}</th>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star4) }}</th>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star5) }}</th>
                <th class="col-1 text-center">{{ form_label(form.blueprint.0.star6) }}</th>
                <th class="col-1 text-center"><label class="fw-light m-0 p-0 form-label">{{ 'text.total'|trans }}</label></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star1 }}" entity="{{ entity.settingBlueprint.star1 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star2 }}" entity="{{ entity.settingBlueprint.star2 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star3 }}" entity="{{ entity.settingBlueprint.star3 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star4 }}" entity="{{ entity.settingBlueprint.star4 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star5 }}" entity="{{ entity.settingBlueprint.star5 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ form.blueprint.0.star6 }}" entity="{{ entity.settingBlueprint.star6 }}" color="{{ text }}" /></td>
                <td><twig:FormGroup3Values form="{{ entity.blueprint.0.total }}" entity="{{ entity.settingBlueprint.total }}" color="{{ text }}" conclusion="true" /></td>
            </tr>
        </tbody>
    </table>
</div>
{#</section>#}

app/templates/front/contents/garage/update/_button.html.twig
<div class="row row-cols-2">
    <div class="col w-25">
        <a href="{{ path(links.index) }}" class="btn btn-lg btn-outline-warning fw-bolder rounded-top-5 rounded-bottom-0 w-100">{{ 'btn.back'|trans }}</a>
    </div>
    <div class="col w-75">
        <button class="btn btn-lg btn-outline-success fw-bolder rounded-top-5 rounded-bottom-0 w-100" type="submit">{{ 'btn.register'|trans }}</button>
    </div>
</div>

app/templates/front/contents/garage/update/_errors.html.twig
{% if form.vars.errors|length > 0 %}
<section class="card py-0 mb-2">
    <div class="card-header bg-secondary-subtle">
        <h6 class="h4 text-center my-0 card-title">{{ 'text.error'|trans|plural }}</h6>
    </div>
    <div class="card-body">
        <div class="row g-3">
            <div class="col">{{ form_errors(form) }}</div>
        </div>
    </div>
</section>
{% else %}
{#    {{ dump(form.vars.errors) }}#}
{% endif %}

app/templates/front/contents/garage/update/_garage-part-1.html.twig
<section class="{{ container|default('container') }} mb-2 px-0">
    <div class="row row-cols-5 mb-3">
        <div class="col-4">
            <twig:FormGroup1Value form="{{ form.settingBrand }}" />
        </div>
        <div class="col-5">
            <twig:FormGroup1Value form="{{ form.model }}" />
        </div>
        <div class="col-1">
            <twig:FormGroup1Value form="{{ form.settingClass }}" />
        </div>
        <div class="col-1">
            <twig:FormGroup1Value form="{{ form.stars }}" />
        </div>
        <div class="col-1">
            <twig:FormGroup1Value form="{{ form.gameUpdate }}" />
        </div>
    </div>
    <div class="row row-cols-9">
        <div class="col-1">
            <twig:FormGroup2Values form="{{ form.level }}" entity="{{ entity.settingLevel.level }}" />
        </div>
        <div class="col-1">
            <twig:FormGroup2Values form="{{ form.epic }}" entity="{{ entity.settingLevel.epic }}" />
        </div>
        <div class="col-1">
            <twig:FormGroup2Values form="{{ form.carOrder }}" entity="{{ entity.settingClass.carsNumber }}" />
        </div>
        <div class="col-1">
            <twig:InputGroup2Values form="{{ entity.statOrder }}" entity="{{ entity.settingClass.carsNumber }}" label="{{ 'text.order.stat'|trans }}" />
        </div>
{#        <div class="col-1">#}
{#            <twig:FormGroup1Value form="{{ form.unblock }}" />#}
{#        </div>#}
{#        <div class="col-1">#}
{#            <twig:FormGroup1Value form="{{ form.gold }}" />#}
{#        </div>#}
        <div class="col-3">
            <twig:FormGroup1Value form="{{ form.settingBlueprint }}" />
        </div>
        <div class="col-2">
            <twig:FormGroup1Value form="{{ form.settingLevel }}" />
        </div>
        <div class="col-3">
            <twig:FormGroup1Value form="{{ form.settingUnitPrice }}" />
        </div>
    </div>
</section>

app/templates/front/contents/garage/update/_nav.html.twig
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button
            class="nav-link active fs-4"
            id="home-tab"
            data-bs-toggle="tab"
            data-bs-target="#home-tab-pane"
            type="button"
            role="tab"
            aria-controls="home-tab-pane"
            aria-selected="true"
        >
            {{ 'text.garage'|trans }}
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button
            class="nav-link fs-4"
            id="profile-tab"
            data-bs-toggle="tab"
            data-bs-target="#profile-tab-pane"
            type="button"
            role="tab"
            aria-controls="profile-tab-pane"
            aria-selected="false"
        >
            {{ 'text.stat'|trans }}
        </button>
    </li>
    <li class="nav-item ms-5" role="presentation">
        <button
            class="nav-link {{ text }} fs-3"
            id="nav-disabled-tab"
            data-bs-toggle="tab"
            data-bs-target="#nav-disabled"
            type="button"
            role="tab"
            aria-controls="nav-disabled"
            aria-selected="false"
            disabled
        >
            {{ car }}
        </button>
    </li>
{#    {% include "@App/front/contents/garage/common/_title.html.twig" %}#}
</ul>

app/templates/front/contents/garage/update/_rank.html.twig
{#<section class="{{ container|default('container') }} mb-2 px-0">#}
<div class="col">
    <h2 class="text-center">{{ 'text.rank'|trans|plural }}</h2>
    <table class="table table-striped table-bordered mb-0">
        <thead>
            <tr>
                <th class="text-center">{{ form_label(form.rank.0.star0) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star1) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star2) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star3) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star4) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star5) }}</th>
                <th class="text-center">{{ form_label(form.rank.0.star6) }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ form_widget(form.rank.0.star0) }}</td>
                <td>{{ form_widget(form.rank.0.star1) }}</td>
                <td>{{ form_widget(form.rank.0.star2) }}</td>
                <td>{{ form_widget(form.rank.0.star3) }}</td>
                <td>{{ form_widget(form.rank.0.star4) }}</td>
                <td>{{ form_widget(form.rank.0.star5) }}</td>
                <td>{{ form_widget(form.rank.0.star6) }}</td>
            </tr>
        </tbody>
    </table>
</div>
{#</section>#}

app/templates/front/contents/garage/update/_stat.html.twig
{#<section class="{{ container|default('container') }} mb-2 px-0">#}
<div class="col-3">
    <h2 class="text-center">{{ 'text.stat'|trans|plural }}</h2>
    <table class="table table-striped table-bordered mb-0">
        <thead>
            <tr>
{#                <th class="text-center">&nbsp;</th>#}
                <th class="text-center">{{ form_label(form.statMin.0.speed) }}</th>
                <th class="text-center">{{ form_label(form.statMin.0.acceleration) }}</th>
                <th class="text-center">{{ form_label(form.statMin.0.handling) }}</th>
                <th class="text-center">{{ form_label(form.statMin.0.nitro) }}</th>
                <th class="text-center">
                    <label class="form-label fw-light m-0 p-0 position-relative" for="{{ 'text.average'|trans }}">
                        {{ 'text.average'|trans }}
                        <span class="position-absolute top-0 start-100 translate-middle-y badge rounded-pill bg-danger">{{ entity.settingClass.median }}</span>
                    </label>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
{#                <td>Min</td>#}
                <td>{{ form_widget(form.statMin.0.speed) }}</td>
                <td>{{ form_widget(form.statMin.0.acceleration) }}</td>
                <td>{{ form_widget(form.statMin.0.handling) }}</td>
                <td>{{ form_widget(form.statMin.0.nitro) }}</td>
                <td>
                    <input type="text" class="text-end fw-bolder m-0 p-0 form-control-plaintext form-control-sm form-control" value="{{ entity.statMin.0.average|number_format('2', ',', ' ') }}">
                </td>
            </tr>
{#            <tr>#}
{#                <td>Actual</td>#}
{#                <td class="text-center fw-bolder">coming soon</td>#}
{#                <td class="text-center fw-bolder">coming soon</td>#}
{#                <td class="text-center fw-bolder">coming soon</td>#}
{#                <td class="text-center fw-bolder">coming soon</td>#}
{#                <td class="text-end fw-bolder">coming soon</td>#}
{#            </tr>#}
            <tr>
{#                <td>Max</td>#}
                <td>{{ form_widget(form.statMax.0.speed) }}</td>
                <td>{{ form_widget(form.statMax.0.acceleration) }}</td>
                <td>{{ form_widget(form.statMax.0.handling) }}</td>
                <td>{{ form_widget(form.statMax.0.nitro) }}</td>
                <td>
                    <input type="text" class="text-end fw-bolder m-0 p-0 form-control-plaintext form-control-sm form-control" value="{{ entity.statMax.0.average|number_format('2', ',', ' ') }}">
                </td>
            </tr>
        </tbody>
    </table>
</div>
{#</section>#}

app/templates/front/contents/garage/update/_status.html.twig
{#<section class="{{ container|default('container') }} mb-2 px-0">#}
<div class="col-3">
    <h2 class="text-center">{{ 'text.status'|trans|plural }}</h2>
        <div class="form-check form-switch">
            {{ form_row(form.status.0.toUpgradeLevel) }}
        </div>
</div>
{#</section>#}

app/templates/front/contents/garage/update/_tag.html.twig
<section class="{{ container|default('container') }} mb-2 px-0">
    <div class="row row-cols-5">
        <div class="col-1">
{#            <twig:FormGroup1Value form="{{ form.unblock }}" />#}
        </div>
        <div class="col-1">
{#            <twig:FormGroup1Value form="{{ form.gold }}" />#}
        </div>
        <div class="col-10">
            <twig:FormGroup1Value form="{{ form.settingTag }}" />
        </div>
    </div>
</section>